name: Make a Release and Deploy on GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18.x"

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          build: npm run build
          start: npm start
          component: true

      - name: Install dependencies
        env:
          HUSKY_SKIP_INSTALL: true
        run: npm ci

      - name: NPM install, build and deploy
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run build
          npm run build:lib
          npx semantic-release
          npm run deploy -- --no-silent --name="Mr. Dharmen's Bot" --email=shhdharmen@gmail.com
