name: Test, Build and Publish a beta version

on:
  push:
    branches-ignore:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"

      - name: Install dependencies
        env:
          HUSKY_SKIP_INSTALL: true
        run: npm ci

      - name: Cypress run
        uses: cypress-io/github-action@v6
        with:
          component: true

      - name: Lint, build and release
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: |
          npm run lint
          npm run build:lib
          npx semantic-release --debug